server:
  port: 8762

spring:
  application:
    name: gateway-server

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1010/eureka
  instance:
    hostname: localhost

zuul:
  ignoredServices: '*'
  routes:
    userService:
      path: /user/**
      serviceId: user-service
      stripPrefix: true
    personService:
      path: /person/**
      serviceId: person-service
      stripPrefix: true
