server:
  port: 1020

spring:
  application:
    name: gateway-server
  mvc:
    dispatchOptionsRequest: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1010/eureka
  instance:
    hostname: localhost

zuul:
  ignoredServices: '*'
  routes:
    securityService:
      path: /security/**
      serviceId: security-service
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie
    userService:
      path: /user/**
      serviceId: user-service
      stripPrefix: false
    personService:
      path: /person/**
      serviceId: person-service
      stripPrefix: false

ribbon:
  ReadTimeout: 60000